version: '2.1'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - url-network
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: urlshortener
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:rw

  app:
    build: .
    ports:
      - 8080:8080
      - 5002:5002
    networks:
      - url-network
    volumes:
      - .:/go/src/urlshortener:rw
    depends_on:
      - postgres
    mem_limit: 1024MB
    cpu_shares: 512

networks:
  url-network:
     driver: bridge
